# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pluggy_sdk.models.asset_distribution import AssetDistribution
from pluggy_sdk.models.percentage_over_index import PercentageOverIndex
from typing import Optional, Set
from typing_extensions import Self

class AggregatedPortfolio(BaseModel):
    """
    Array of Aggregated Portfolio by period indicated
    """ # noqa: E501
    balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Current balance from total portfolio of assets")
    percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage yield compared to the previous month")
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount yield over the period")
    currency: Optional[StrictStr] = Field(default=None, description="Currency of the yield amount")
    var_date: Optional[StrictStr] = Field(default=None, description="Date when the porfolio was captured", alias="date")
    percentage_over_index: Optional[PercentageOverIndex] = Field(default=None, alias="percentageOverIndex")
    period: Optional[StrictStr] = Field(default=None, description="Period from AggregatedPortfolio was retrieved")
    asset_distribution: Optional[AssetDistribution] = Field(default=None, alias="assetDistribution")
    __properties: ClassVar[List[str]] = ["balance", "percentage", "amount", "currency", "date", "percentageOverIndex", "period", "assetDistribution"]

    @field_validator('period')
    def period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CURRENT_YEAR', 'LAST_TWELVE_MONTHS']):
            raise ValueError("must be one of enum values ('CURRENT_YEAR', 'LAST_TWELVE_MONTHS')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AggregatedPortfolio from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of percentage_over_index
        if self.percentage_over_index:
            _dict['percentageOverIndex'] = self.percentage_over_index.to_dict()
        # override the default output from pydantic by calling `to_dict()` of asset_distribution
        if self.asset_distribution:
            _dict['assetDistribution'] = self.asset_distribution.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AggregatedPortfolio from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "balance": obj.get("balance"),
            "percentage": obj.get("percentage"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "date": obj.get("date"),
            "percentageOverIndex": PercentageOverIndex.from_dict(obj["percentageOverIndex"]) if obj.get("percentageOverIndex") is not None else None,
            "period": obj.get("period"),
            "assetDistribution": AssetDistribution.from_dict(obj["assetDistribution"]) if obj.get("assetDistribution") is not None else None
        })
        return _obj


