# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pluggy_sdk.models.reserved_balance import ReservedBalance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BankData(BaseModel):
    """
    Bank account additional fields
    """ # noqa: E501
    transfer_number: Optional[StrictStr] = Field(default=None, description="Complete number of the bank account `(agency code / account number)`", alias="transferNumber")
    closing_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Balance including not posted transactions", alias="closingBalance")
    automatically_invested_balance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Balance automatically invested in the account by the FI", alias="automaticallyInvestedBalance")
    overdraft_contracted_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Overdraft contracted limit", alias="overdraftContractedLimit")
    overdraft_used_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Overdraft used limit", alias="overdraftUsedLimit")
    unarranged_overdraft_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Valor de operação contratada em caráter emergencial para cobertura de saldo devedor em conta de depósitos à vista e de excesso sobre o limite pactuado de cheque especial.", alias="unarrangedOverdraftAmount")
    has_reserved_balance: Optional[StrictBool] = Field(default=None, description="Whether the account has any active reserved balances (\"saldo reservado\"), such as goal-based savings (\"caixinhas\") or judicial holds", alias="hasReservedBalance")
    reserved_balances: Optional[List[ReservedBalance]] = Field(default=None, description="Funds reserved/earmarked on the account. Only present when hasReservedBalance is true and the institution exposes the data", alias="reservedBalances")
    __properties: ClassVar[List[str]] = ["transferNumber", "closingBalance", "automaticallyInvestedBalance", "overdraftContractedLimit", "overdraftUsedLimit", "unarrangedOverdraftAmount", "hasReservedBalance", "reservedBalances"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reserved_balances (list)
        _items = []
        if self.reserved_balances:
            for _item_reserved_balances in self.reserved_balances:
                if _item_reserved_balances:
                    _items.append(_item_reserved_balances.to_dict())
            _dict['reservedBalances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transferNumber": obj.get("transferNumber"),
            "closingBalance": obj.get("closingBalance"),
            "automaticallyInvestedBalance": obj.get("automaticallyInvestedBalance"),
            "overdraftContractedLimit": obj.get("overdraftContractedLimit"),
            "overdraftUsedLimit": obj.get("overdraftUsedLimit"),
            "unarrangedOverdraftAmount": obj.get("unarrangedOverdraftAmount"),
            "hasReservedBalance": obj.get("hasReservedBalance"),
            "reservedBalances": [ReservedBalance.from_dict(_item) for _item in obj["reservedBalances"]] if obj.get("reservedBalances") is not None else None
        })
        return _obj


