# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DisaggregatedCreditLimit(BaseModel):
    """
    Disaggregated credit card limit
    """ # noqa: E501
    credit_line_limit_type: StrictStr = Field(description="Limit type (LIMITE_CREDITO_TOTAL or LIMITE_CREDITO_MODALIDADE_OPERACAO)", alias="creditLineLimitType")
    consolidation_type: StrictStr = Field(description="Indicates if the limit is consolidated or individual", alias="consolidationType")
    identification_number: StrictStr = Field(description="Identification number of the additional credit card", alias="identificationNumber")
    is_limit_flexible: StrictBool = Field(description="Indicates if the limit is flexible", alias="isLimitFlexible")
    used_amount: Union[StrictFloat, StrictInt] = Field(description="Used amount of the additional credit card", alias="usedAmount")
    used_amount_currency_code: StrictStr = Field(description="Used amount currency code (for example, BRL)", alias="usedAmountCurrencyCode")
    line_name: Optional[StrictStr] = Field(default=None, description="Name of the credit limit line", alias="lineName")
    line_name_additional_info: Optional[StrictStr] = Field(default=None, description="Free text describing the line name when lineName is 'OUTROS'", alias="lineNameAdditionalInfo")
    limit_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Limit amount of the additional credit card", alias="limitAmount")
    limit_amount_currency_code: Optional[StrictStr] = Field(default=None, description="Limit amount currency code (for example, BRL)", alias="limitAmountCurrencyCode")
    limit_amount_reason: Optional[StrictStr] = Field(default=None, description="Reason why the reported total limit amount is equal to zero", alias="limitAmountReason")
    customized_limit_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total limit amount customized by the customer through the institution's electronic channels", alias="customizedLimitAmount")
    customized_limit_amount_currency_code: Optional[StrictStr] = Field(default=None, description="Customized limit amount currency code (for example, BRL)", alias="customizedLimitAmountCurrencyCode")
    available_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Available amount of the additional credit card", alias="availableAmount")
    available_amount_currency_code: Optional[StrictStr] = Field(default=None, description="Available amount currency code (for example, BRL)", alias="availableAmountCurrencyCode")
    __properties: ClassVar[List[str]] = ["creditLineLimitType", "consolidationType", "identificationNumber", "isLimitFlexible", "usedAmount", "usedAmountCurrencyCode", "lineName", "lineNameAdditionalInfo", "limitAmount", "limitAmountCurrencyCode", "limitAmountReason", "customizedLimitAmount", "customizedLimitAmountCurrencyCode", "availableAmount", "availableAmountCurrencyCode"]

    @field_validator('line_name')
    def line_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREDITO_A_VISTA', 'CREDITO_PARCELADO', 'SAQUE_CREDITO_BRASIL', 'SAQUE_CREDITO_EXTERIOR', 'EMPRESTIMO_CARTAO_CONSIGNADO', 'OUTROS']):
            raise ValueError("must be one of enum values ('CREDITO_A_VISTA', 'CREDITO_PARCELADO', 'SAQUE_CREDITO_BRASIL', 'SAQUE_CREDITO_EXTERIOR', 'EMPRESTIMO_CARTAO_CONSIGNADO', 'OUTROS')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DisaggregatedCreditLimit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DisaggregatedCreditLimit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creditLineLimitType": obj.get("creditLineLimitType"),
            "consolidationType": obj.get("consolidationType"),
            "identificationNumber": obj.get("identificationNumber"),
            "isLimitFlexible": obj.get("isLimitFlexible"),
            "usedAmount": obj.get("usedAmount"),
            "usedAmountCurrencyCode": obj.get("usedAmountCurrencyCode"),
            "lineName": obj.get("lineName"),
            "lineNameAdditionalInfo": obj.get("lineNameAdditionalInfo"),
            "limitAmount": obj.get("limitAmount"),
            "limitAmountCurrencyCode": obj.get("limitAmountCurrencyCode"),
            "limitAmountReason": obj.get("limitAmountReason"),
            "customizedLimitAmount": obj.get("customizedLimitAmount"),
            "customizedLimitAmountCurrencyCode": obj.get("customizedLimitAmountCurrencyCode"),
            "availableAmount": obj.get("availableAmount"),
            "availableAmountCurrencyCode": obj.get("availableAmountCurrencyCode")
        })
        return _obj


