# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pluggy_sdk.models.identity_response_financial_relationships_accounts_inner import IdentityResponseFinancialRelationshipsAccountsInner
from pluggy_sdk.models.identity_response_financial_relationships_procurators_inner import IdentityResponseFinancialRelationshipsProcuratorsInner
from pluggy_sdk.models.paycheck_bank_link import PaycheckBankLink
from pluggy_sdk.models.portability_received import PortabilityReceived
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IdentityResponseFinancialRelationships(BaseModel):
    """
    Information that allows institutions to assess, evaluate, characterize, and classify the client with the purpose of understanding their risk profile and their economic-financial capacity
    """ # noqa: E501
    start_date: datetime = Field(description="Date when the relationship with the institution started", alias="startDate")
    products_services_type: List[StrictStr] = Field(description="List of products and services that the client consumes", alias="productsServicesType")
    products_services_type_additional_info: Optional[StrictStr] = Field(default=None, description="Additional info about the products and services. Populated when productsServicesType includes 'OUTROS'", alias="productsServicesTypeAdditionalInfo")
    procurators: List[IdentityResponseFinancialRelationshipsProcuratorsInner] = Field(description="List of procurators of the client")
    accounts: Optional[List[IdentityResponseFinancialRelationshipsAccountsInner]] = Field(default=None, description="List of accounts of the client with valid consent. Only accounts that have explicit user consent are returned.")
    portabilities_received: Optional[List[PortabilityReceived]] = Field(default=None, description="Salary portabilities received by the institution from the client's previous paycheck banks (banco-folha). PF-only field", alias="portabilitiesReceived")
    paychecks_bank_link: Optional[List[PaycheckBankLink]] = Field(default=None, description="Paycheck-bank (banco-folha) links to employers, active or formerly active. PF-only field", alias="paychecksBankLink")
    __properties: ClassVar[List[str]] = ["startDate", "productsServicesType", "productsServicesTypeAdditionalInfo", "procurators", "accounts", "portabilitiesReceived", "paychecksBankLink"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentityResponseFinancialRelationships from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in procurators (list)
        _items = []
        if self.procurators:
            for _item_procurators in self.procurators:
                if _item_procurators:
                    _items.append(_item_procurators.to_dict())
            _dict['procurators'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item_accounts in self.accounts:
                if _item_accounts:
                    _items.append(_item_accounts.to_dict())
            _dict['accounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in portabilities_received (list)
        _items = []
        if self.portabilities_received:
            for _item_portabilities_received in self.portabilities_received:
                if _item_portabilities_received:
                    _items.append(_item_portabilities_received.to_dict())
            _dict['portabilitiesReceived'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in paychecks_bank_link (list)
        _items = []
        if self.paychecks_bank_link:
            for _item_paychecks_bank_link in self.paychecks_bank_link:
                if _item_paychecks_bank_link:
                    _items.append(_item_paychecks_bank_link.to_dict())
            _dict['paychecksBankLink'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentityResponseFinancialRelationships from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startDate": obj.get("startDate"),
            "productsServicesType": obj.get("productsServicesType"),
            "productsServicesTypeAdditionalInfo": obj.get("productsServicesTypeAdditionalInfo"),
            "procurators": [IdentityResponseFinancialRelationshipsProcuratorsInner.from_dict(_item) for _item in obj["procurators"]] if obj.get("procurators") is not None else None,
            "accounts": [IdentityResponseFinancialRelationshipsAccountsInner.from_dict(_item) for _item in obj["accounts"]] if obj.get("accounts") is not None else None,
            "portabilitiesReceived": [PortabilityReceived.from_dict(_item) for _item in obj["portabilitiesReceived"]] if obj.get("portabilitiesReceived") is not None else None,
            "paychecksBankLink": [PaycheckBankLink.from_dict(_item) for _item in obj["paychecksBankLink"]] if obj.get("paychecksBankLink") is not None else None
        })
        return _obj


