# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from pluggy_sdk.models.investment_expenses import InvestmentExpenses
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InvestmentTransaction(BaseModel):
    """
    Movement of the investment
    """ # noqa: E501
    id: StrictStr = Field(description="Primary investment transaction identifier")
    type: StrictStr = Field(description="Operation performed on the investment position. - `BUY`: subscription / purchase of new quotas. - `SELL`: redemption / sale of quotas. - `TRANSFER`: portability or internal transfer between accounts (the `amount` field may be null). - `TAX`: tax withholdings such as IR or IOF. - `INTEREST`: interest or yield credited to the position. - `AMORTIZATION`: principal repayment (typical of fixed-income amortizing bonds).")
    movement_type: Optional[StrictStr] = Field(default=None, description="Cash-flow direction of the transaction from the holder's perspective. - `CREDIT`: money goes into the position (defaults for `BUY`). - `DEBIT`: money leaves the position (defaults for `SELL`, `TAX`, `TRANSFER`, `INTEREST`, `AMORTIZATION`).", alias="movementType")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Quantity of the transaction")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Value on the transaction's Date")
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Gross amount of the operation. May be null only if type is TRANSFER")
    agreed_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Agreed rate for treasury applications", alias="agreedRate")
    indexer_percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Max percentage of the indexer agreed at contracting (e.g. 110% of CDI)", alias="indexerPercentage")
    price_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="B3 lot/price conversion factor (variable income transactions)", alias="priceFactor")
    var_date: datetime = Field(description="Date when the transaction was made", alias="date")
    trade_date: Optional[datetime] = Field(default=None, description="Date when the transaction was confirmed", alias="tradeDate")
    expenses: Optional[InvestmentExpenses] = None
    description: Optional[StrictStr] = Field(default=None, description="Description of the transaction as reported by the institution")
    net_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount of the operation after expenses and taxes", alias="netAmount")
    brokerage_number: Optional[StrictStr] = Field(default=None, description="Brokerage note number the transaction belongs to", alias="brokerageNumber")
    __properties: ClassVar[List[str]] = ["id", "type", "movementType", "quantity", "value", "amount", "agreedRate", "indexerPercentage", "priceFactor", "date", "tradeDate", "expenses", "description", "netAmount", "brokerageNumber"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BUY', 'SELL', 'TAX', 'TRANSFER', 'INTEREST', 'AMORTIZATION']):
            raise ValueError("must be one of enum values ('BUY', 'SELL', 'TAX', 'TRANSFER', 'INTEREST', 'AMORTIZATION')")
        return value

    @field_validator('movement_type')
    def movement_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREDIT', 'DEBIT']):
            raise ValueError("must be one of enum values ('CREDIT', 'DEBIT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvestmentTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of expenses
        if self.expenses:
            _dict['expenses'] = self.expenses.to_dict()
        # set to None if movement_type (nullable) is None
        # and model_fields_set contains the field
        if self.movement_type is None and "movement_type" in self.model_fields_set:
            _dict['movementType'] = None

        # set to None if quantity (nullable) is None
        # and model_fields_set contains the field
        if self.quantity is None and "quantity" in self.model_fields_set:
            _dict['quantity'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if agreed_rate (nullable) is None
        # and model_fields_set contains the field
        if self.agreed_rate is None and "agreed_rate" in self.model_fields_set:
            _dict['agreedRate'] = None

        # set to None if indexer_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.indexer_percentage is None and "indexer_percentage" in self.model_fields_set:
            _dict['indexerPercentage'] = None

        # set to None if price_factor (nullable) is None
        # and model_fields_set contains the field
        if self.price_factor is None and "price_factor" in self.model_fields_set:
            _dict['priceFactor'] = None

        # set to None if trade_date (nullable) is None
        # and model_fields_set contains the field
        if self.trade_date is None and "trade_date" in self.model_fields_set:
            _dict['tradeDate'] = None

        # set to None if expenses (nullable) is None
        # and model_fields_set contains the field
        if self.expenses is None and "expenses" in self.model_fields_set:
            _dict['expenses'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if net_amount (nullable) is None
        # and model_fields_set contains the field
        if self.net_amount is None and "net_amount" in self.model_fields_set:
            _dict['netAmount'] = None

        # set to None if brokerage_number (nullable) is None
        # and model_fields_set contains the field
        if self.brokerage_number is None and "brokerage_number" in self.model_fields_set:
            _dict['brokerageNumber'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvestmentTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "movementType": obj.get("movementType"),
            "quantity": obj.get("quantity"),
            "value": obj.get("value"),
            "amount": obj.get("amount"),
            "agreedRate": obj.get("agreedRate"),
            "indexerPercentage": obj.get("indexerPercentage"),
            "priceFactor": obj.get("priceFactor"),
            "date": obj.get("date"),
            "tradeDate": obj.get("tradeDate"),
            "expenses": InvestmentExpenses.from_dict(obj["expenses"]) if obj.get("expenses") is not None else None,
            "description": obj.get("description"),
            "netAmount": obj.get("netAmount"),
            "brokerageNumber": obj.get("brokerageNumber")
        })
        return _obj


