# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from pluggy_sdk.models.nationality_other_nationalities_inner import NationalityOtherNationalitiesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Nationality(BaseModel):
    """
    Nationality of the natural person
    """ # noqa: E501
    has_brazilian_nationality: StrictBool = Field(description="Whether the client has Brazilian nationality", alias="hasBrazilianNationality")
    other_nationalities: Optional[List[NationalityOtherNationalitiesInner]] = Field(default=None, description="Other nationalities held by the client, if any", alias="otherNationalities")
    __properties: ClassVar[List[str]] = ["hasBrazilianNationality", "otherNationalities"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Nationality from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in other_nationalities (list)
        _items = []
        if self.other_nationalities:
            for _item_other_nationalities in self.other_nationalities:
                if _item_other_nationalities:
                    _items.append(_item_other_nationalities.to_dict())
            _dict['otherNationalities'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Nationality from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hasBrazilianNationality": obj.get("hasBrazilianNationality"),
            "otherNationalities": [NationalityOtherNationalitiesInner.from_dict(_item) for _item in obj["otherNationalities"]] if obj.get("otherNationalities") is not None else None
        })
        return _obj


