# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentCustomerType(str, Enum):
    """
    Customer type. - `INDIVIDUAL`: identified by `cpf`. - `BUSINESS`: identified by `cnpj`.
    """

    """
    allowed enum values
    """
    INDIVIDUAL = 'INDIVIDUAL'
    BUSINESS = 'BUSINESS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentCustomerType from a JSON string"""
        return cls(json.loads(json_str))


