# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from pluggy_sdk.models.scr_database import ScrDatabase
from pluggy_sdk.models.scr_validation_message import ScrValidationMessage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScrResponse(BaseModel):
    """
    Bacen's SCR response, forwarded exactly as the Banco Central returns it — field names, codes and all. Nothing is renamed or normalised, so a value read here is the same value an institution reads at the source.
    """ # noqa: E501
    dtb_consult: StrictStr = Field(description="The base dates consulted", alias="dtbConsult", json_schema_extra={"examples": ["202604 a 202607"]})
    cd_cli: StrictStr = Field(description="The consulted document: the CPF for an individual, or the 8-digit CNPJ root for a company", alias="cdCli")
    tp_cli: StrictStr = Field(description="Type of client: \"1\" for an individual, \"2\" for a legal entity", alias="tpCli")
    ls_dtb: Optional[List[ScrDatabase]] = Field(default=None, description="One entry per consulted base date. A base date with no data for the client is still listed, with no operations", alias="lsDtb")
    lista_de_mensagens_de_validacao: Optional[List[ScrValidationMessage]] = Field(default=None, description="Validation messages raised by Bacen for this request", alias="listaDeMensagensDeValidacao")
    __properties: ClassVar[List[str]] = ["dtbConsult", "cdCli", "tpCli", "lsDtb", "listaDeMensagensDeValidacao"]

    @field_validator('tp_cli')
    def tp_cli_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2']):
            raise ValueError("must be one of enum values ('1', '2')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ls_dtb (list)
        _items = []
        if self.ls_dtb:
            for _item_ls_dtb in self.ls_dtb:
                _items.append(_item_ls_dtb.to_dict() if _item_ls_dtb is not None else None)
            _dict['lsDtb'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lista_de_mensagens_de_validacao (list)
        _items = []
        if self.lista_de_mensagens_de_validacao:
            for _item_lista_de_mensagens_de_validacao in self.lista_de_mensagens_de_validacao:
                _items.append(_item_lista_de_mensagens_de_validacao.to_dict() if _item_lista_de_mensagens_de_validacao is not None else None)
            _dict['listaDeMensagensDeValidacao'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dtbConsult": obj.get("dtbConsult"),
            "cdCli": obj.get("cdCli"),
            "tpCli": obj.get("tpCli"),
            "lsDtb": [ScrDatabase.from_dict(_item) for _item in obj["lsDtb"]] if obj.get("lsDtb") is not None else None,
            "listaDeMensagensDeValidacao": [ScrValidationMessage.from_dict(_item) for _item in obj["listaDeMensagensDeValidacao"]] if obj.get("listaDeMensagensDeValidacao") is not None else None
        })
        return _obj


