# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pluggy_sdk.models.scr_additional_info import ScrAdditionalInfo
from pluggy_sdk.models.scr_guarantee import ScrGuarantee
from pluggy_sdk.models.scr_maturity_balances import ScrMaturityBalances
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScrOperation(BaseModel):
    """
    A group of credit operations. The SCR does not return contracts one by one: it aggregates them by the combination of modality, source of funds, index and exchange variation.
    """ # noqa: E501
    mod: Optional[StrictStr] = Field(default=None, description="Bacen's code for the operation modality")
    ori_rec: Optional[StrictStr] = Field(default=None, description="Bacen's code for the source of funds", alias="oriRec")
    indx: Optional[StrictStr] = Field(default=None, description="Bacen's code for the reference rate or index")
    var_camb: Optional[StrictStr] = Field(default=None, description="Bacen's code for the exchange rate variation", alias="varCamb")
    sub_j_disc: Optional[StrictStr] = Field(default=None, description="Present when the operation is under dispute: \"D\" for disagreement, \"J\" for sub judice, \"JD\" for both", alias="subJDisc")
    res_venc: Optional[ScrMaturityBalances] = Field(default=None, alias="resVenc")
    ls_gar: Optional[List[ScrGuarantee]] = Field(default=None, description="Guarantees backing the operations in this group", alias="lsGar")
    ls_inf_ad: Optional[List[ScrAdditionalInfo]] = Field(default=None, description="Complementary information reported for this group", alias="lsInfAd")
    __properties: ClassVar[List[str]] = ["mod", "oriRec", "indx", "varCamb", "subJDisc", "resVenc", "lsGar", "lsInfAd"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of res_venc
        if self.res_venc:
            _dict['resVenc'] = self.res_venc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ls_gar (list)
        _items = []
        if self.ls_gar:
            for _item_ls_gar in self.ls_gar:
                _items.append(_item_ls_gar.to_dict() if _item_ls_gar is not None else None)
            _dict['lsGar'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in ls_inf_ad (list)
        _items = []
        if self.ls_inf_ad:
            for _item_ls_inf_ad in self.ls_inf_ad:
                _items.append(_item_ls_inf_ad.to_dict() if _item_ls_inf_ad is not None else None)
            _dict['lsInfAd'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mod": obj.get("mod"),
            "oriRec": obj.get("oriRec"),
            "indx": obj.get("indx"),
            "varCamb": obj.get("varCamb"),
            "subJDisc": obj.get("subJDisc"),
            "resVenc": ScrMaturityBalances.from_dict(obj["resVenc"]) if obj.get("resVenc") is not None else None,
            "lsGar": [ScrGuarantee.from_dict(_item) for _item in obj["lsGar"]] if obj.get("lsGar") is not None else None,
            "lsInfAd": [ScrAdditionalInfo.from_dict(_item) for _item in obj["lsInfAd"]] if obj.get("lsInfAd") is not None else None
        })
        return _obj


