# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SmartTransferPaymentStatus(str, Enum):
    """
    Lifecycle of a Smart Transfer payment. Narrower than `PaymentIntentStatus`: Smart Transfer payments operate under an already-authorized preauthorization, so consent-collection statuses (`STARTED`, `ENQUEUED`, `CONSENT_AWAITING_AUTHORIZATION`) and consent-revocation statuses (`REJECTED`, `REVOKED`, `CONSUMED`) do not apply. - `CONSENT_AUTHORIZED`: the payment was accepted under the preauthorization and is ready to be processed. - `CONSENT_REJECTED`: the preauthorization was rejected at execution time. - `PAYMENT_PENDING`: the payment was submitted to the institution and is awaiting confirmation. - `PAYMENT_PARTIALLY_ACCEPTED`: the payment was accepted but still needs an additional authorization. - `PAYMENT_SETTLEMENT_PROCESSING`: the settlement is being processed. - `PAYMENT_SETTLEMENT_DEBTOR_ACCOUNT`: the funds were debited from the payer account; awaiting clearing. - `PAYMENT_COMPLETED`: the payment was confirmed by the institution. - `PAYMENT_REJECTED`: the payment was rejected after consent was authorized. - `ERROR`: an unexpected error occurred during the flow. - `CANCELED`: the payment was canceled.
    """

    """
    allowed enum values
    """
    CONSENT_AUTHORIZED = 'CONSENT_AUTHORIZED'
    CONSENT_REJECTED = 'CONSENT_REJECTED'
    PAYMENT_PENDING = 'PAYMENT_PENDING'
    PAYMENT_PARTIALLY_ACCEPTED = 'PAYMENT_PARTIALLY_ACCEPTED'
    PAYMENT_SETTLEMENT_PROCESSING = 'PAYMENT_SETTLEMENT_PROCESSING'
    PAYMENT_SETTLEMENT_DEBTOR_ACCOUNT = 'PAYMENT_SETTLEMENT_DEBTOR_ACCOUNT'
    PAYMENT_COMPLETED = 'PAYMENT_COMPLETED'
    PAYMENT_REJECTED = 'PAYMENT_REJECTED'
    ERROR = 'ERROR'
    CANCELED = 'CANCELED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SmartTransferPaymentStatus from a JSON string"""
        return cls(json.loads(json_str))


