# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.api.payment_request_api import PaymentRequestApi


class TestPaymentRequestApi(unittest.TestCase):
    """PaymentRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentRequestApi()

    def tearDown(self) -> None:
        pass

    def test_payment_request_create(self) -> None:
        """Test case for payment_request_create

        Create
        """
        pass

    def test_payment_request_create_pix_qr(self) -> None:
        """Test case for payment_request_create_pix_qr

        Create PIX QR payment request
        """
        pass

    def test_payment_request_delete(self) -> None:
        """Test case for payment_request_delete

        Delete
        """
        pass

    def test_payment_request_retrieve(self) -> None:
        """Test case for payment_request_retrieve

        Retrieve
        """
        pass

    def test_payment_request_update(self) -> None:
        """Test case for payment_request_update

        Update
        """
        pass

    def test_payment_requests_list(self) -> None:
        """Test case for payment_requests_list

        List
        """
        pass


if __name__ == '__main__':
    unittest.main()
