# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.api.acquirer_receivable_api import AcquirerReceivableApi


class TestAcquirerReceivableApi(unittest.TestCase):
    """AcquirerReceivableApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AcquirerReceivableApi()

    def tearDown(self) -> None:
        pass

    def test_acquirer_receivable_retrieve(self) -> None:
        """Test case for acquirer_receivable_retrieve

        Retrieve
        """
        pass

    def test_acquirer_receivables_list(self) -> None:
        """Test case for acquirer_receivables_list

        List
        """
        pass


if __name__ == '__main__':
    unittest.main()
