# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.automatic_pix import AutomaticPix

class TestAutomaticPix(unittest.TestCase):
    """AutomaticPix unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutomaticPix:
        """Test AutomaticPix
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutomaticPix`
        """
        model = AutomaticPix()
        if include_optional:
            return AutomaticPix(
                fixed_amount = 1.337,
                minimum_variable_amount = 1.337,
                maximum_variable_amount = 1.337,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_retry_accepted = True,
                first_payment = pluggy_sdk.models.automatic_pix_first_payment.AutomaticPixFirstPayment(
                    date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '', 
                    amount = 1.337, ),
                interval = 'WEEKLY',
                automatic_retries_configuration = pluggy_sdk.models.automatic_pix_retries_configuration.AutomaticPixRetriesConfiguration(
                    retry_days = [
                        1
                        ], ),
                scheduler_configuration = pluggy_sdk.models.automatic_pix_scheduler_configuration.AutomaticPixSchedulerConfiguration(
                    enabled = True, 
                    description = '', 
                    value_for_variable_amount = 0.01, )
            )
        else:
            return AutomaticPix(
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                interval = 'WEEKLY',
        )
        """

    def testAutomaticPix(self):
        """Test AutomaticPix"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
