# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.smart_account_transfer import SmartAccountTransfer

class TestSmartAccountTransfer(unittest.TestCase):
    """SmartAccountTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmartAccountTransfer:
        """Test SmartAccountTransfer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmartAccountTransfer`
        """
        model = SmartAccountTransfer()
        if include_optional:
            return SmartAccountTransfer(
                id = '',
                client_id = '',
                client_payment_id = '',
                amount = 1.337,
                status = 'IN_PROGRESS',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                smart_account = {"id":"71996b6d-8991-450c-8542-ae59069d1a9d","ispb":"0001020","agency":"1234","number":"123456","verifyingDigit":"7","type":"CHECKING_ACCOUNT","isSandbox":false},
                payment_recipient = {"id":"5e9f8f8f-f8f8-4f8f-8f8f-8f8f8f8f8f8f","name":"Conta empresa","taxNumber":"123456789-00","paymentInstitution":{"id":"00000000-0000-0000-0000-000000000000","name":"Banco J. Safra S.A.","ispb":"03017677","tradeName":"Banco Safra","compe":"074","createdAt":"2020-04-21T15:00:00.000Z","updatedAt":"2020-04-21T15:00:00.000Z"},"account":{"branch":"0001","number":"123456","type":"CHECKING_ACCOUNT"},"isDefault":true,"pixKey":null}
            )
        else:
            return SmartAccountTransfer(
        )
        """

    def testSmartAccountTransfer(self):
        """Test SmartAccountTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
