# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.api.benefit_api import BenefitApi


class TestBenefitApi(unittest.TestCase):
    """BenefitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BenefitApi()

    def tearDown(self) -> None:
        pass

    def test_benefit_retrieve_by_id(self) -> None:
        """Test case for benefit_retrieve_by_id

        Retrieve
        """
        pass

    def test_benefits_list(self) -> None:
        """Test case for benefits_list

        List
        """
        pass


if __name__ == '__main__':
    unittest.main()
