# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.create_payment_request_schedule import CreatePaymentRequestSchedule

class TestCreatePaymentRequestSchedule(unittest.TestCase):
    """CreatePaymentRequestSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePaymentRequestSchedule:
        """Test CreatePaymentRequestSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePaymentRequestSchedule`
        """
        model = CreatePaymentRequestSchedule()
        if include_optional:
            return CreatePaymentRequestSchedule(
                type = 'SINGLE',
                var_date = 'Tue Jun 11 00:00:00 UTC 2024',
                start_date = 'Tue Jun 11 00:00:00 UTC 2024',
                occurrences = 3,
                day_of_week = 'MONDAY',
                day_of_month = 3,
                dates = [
                    'Tue Jun 11 00:00:00 UTC 2024'
                    ],
                additional_information = ''
            )
        else:
            return CreatePaymentRequestSchedule(
                type = 'SINGLE',
                var_date = 'Tue Jun 11 00:00:00 UTC 2024',
                start_date = 'Tue Jun 11 00:00:00 UTC 2024',
                day_of_week = 'MONDAY',
                day_of_month = 3,
                dates = [
                    'Tue Jun 11 00:00:00 UTC 2024'
                    ],
        )
        """

    def testCreatePaymentRequestSchedule(self):
        """Test CreatePaymentRequestSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
