# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.status_detail_product import StatusDetailProduct

class TestStatusDetailProduct(unittest.TestCase):
    """StatusDetailProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusDetailProduct:
        """Test StatusDetailProduct
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusDetailProduct`
        """
        model = StatusDetailProduct()
        if include_optional:
            return StatusDetailProduct(
                last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_updated = True,
                warnings = [
                    pluggy_sdk.models.status_detail_product_warning.StatusDetailProductWarning(
                        code = '', 
                        message = '', 
                        provider_message = '', )
                    ]
            )
        else:
            return StatusDetailProduct(
        )
        """

    def testStatusDetailProduct(self):
        """Test StatusDetailProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
