# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.automatic_pix_interval import AutomaticPixInterval

class TestAutomaticPixInterval(unittest.TestCase):
    """AutomaticPixInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutomaticPixInterval(self):
        """Test AutomaticPixInterval"""
        # inst = AutomaticPixInterval()

if __name__ == '__main__':
    unittest.main()
