# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_accounts_list(self) -> None:
        """Test case for accounts_list

        List
        """
        pass

    def test_accounts_retrieve(self) -> None:
        """Test case for accounts_retrieve

        Retrieve
        """
        pass


if __name__ == '__main__':
    unittest.main()
