# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.credit_data import CreditData

class TestCreditData(unittest.TestCase):
    """CreditData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditData:
        """Test CreditData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditData`
        """
        model = CreditData()
        if include_optional:
            return CreditData(
                level = '',
                brand = '',
                balance_close_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                balance_due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                available_credit_limit = 1.337,
                balance_foreign_currency = 1.337,
                minimum_payment = 1.337,
                credit_limit = 1.337,
                status = 'ACTIVE',
                holder_type = 'MAIN'
            )
        else:
            return CreditData(
        )
        """

    def testCreditData(self):
        """Test CreditData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
