# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.api.investment_api import InvestmentApi


class TestInvestmentApi(unittest.TestCase):
    """InvestmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvestmentApi()

    def tearDown(self) -> None:
        pass

    def test_investment_transactions_list(self) -> None:
        """Test case for investment_transactions_list

        List investment transactions
        """
        pass

    def test_investments_list(self) -> None:
        """Test case for investments_list

        List
        """
        pass

    def test_investments_retrieve(self) -> None:
        """Test case for investments_retrieve

        Retrieve
        """
        pass


if __name__ == '__main__':
    unittest.main()
