# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.scr_database import ScrDatabase

class TestScrDatabase(unittest.TestCase):
    """ScrDatabase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScrDatabase:
        """Test ScrDatabase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScrDatabase`
        """
        model = ScrDatabase()
        if include_optional:
            return ScrDatabase(
                dtb = 202607,
                msg = '',
                doc_proc = '',
                vol_proc = '',
                qtd_ifs = 1.337,
                qtd_cong_finc = 1.337,
                dtb_ini_rel = '',
                coob_ass = 1.337,
                coob_rec = 1.337,
                ls_op = [
                    pluggy_sdk.models.scr_operation.SCR Operation(
                        mod = '', 
                        ori_rec = '', 
                        indx = '', 
                        var_camb = '', 
                        sub_j_disc = '', 
                        res_venc = pluggy_sdk.models.scr_maturity_balances.SCR Maturity Balances(
                            v20 = 1.337, 
                            v40 = 1.337, 
                            v60 = 1.337, 
                            v80 = 1.337, 
                            v110 = 1.337, 
                            v120 = 1.337, 
                            v130 = 1.337, 
                            v140 = 1.337, 
                            v150 = 1.337, 
                            v160 = 1.337, 
                            v165 = 1.337, 
                            v170 = 1.337, 
                            v175 = 1.337, 
                            v180 = 1.337, 
                            v190 = 1.337, 
                            v199 = 1.337, 
                            v205 = 1.337, 
                            v210 = 1.337, 
                            v220 = 1.337, 
                            v230 = 1.337, 
                            v240 = 1.337, 
                            v245 = 1.337, 
                            v250 = 1.337, 
                            v255 = 1.337, 
                            v260 = 1.337, 
                            v270 = 1.337, 
                            v280 = 1.337, 
                            v290 = 1.337, 
                            v310 = 1.337, 
                            v320 = 1.337, ), 
                        ls_gar = [
                            pluggy_sdk.models.scr_guarantee.SCR Guarantee(
                                tp = '', 
                                qtd = 1.337, )
                            ], 
                        ls_inf_ad = [
                            pluggy_sdk.models.scr_additional_info.SCR Additional Info(
                                tp = '', 
                                cd = '', 
                                qtd = 1.337, )
                            ], )
                    ]
            )
        else:
            return ScrDatabase(
        )
        """

    def testScrDatabase(self):
        """Test ScrDatabase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
