# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.payment_intents_list200_response import PaymentIntentsList200Response

class TestPaymentIntentsList200Response(unittest.TestCase):
    """PaymentIntentsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentIntentsList200Response:
        """Test PaymentIntentsList200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentIntentsList200Response`
        """
        model = PaymentIntentsList200Response()
        if include_optional:
            return PaymentIntentsList200Response(
                page = 1.337,
                total = 1.337,
                total_pages = 1.337,
                results = [
                    {"id":"4cfe1f6d-ae71-4c35-aae0-8f8a535ffbbd","status":"CONSENT_AWAITING_AUTHORIZATION","createdAt":"2023-11-06T15:38:47.861Z","updatedAt":"2023-11-06T15:45:19.384Z","paymentRequest":{"id":"c2a6b7d9-3349-435d-8341-44021449ebbc","amount":100.5,"description":"Transferência","status":"IN_PROGRESS","createdAt":"2023-11-06T13:03:45.689Z","updatedAt":"2023-11-06T15:45:19.401Z","callbackUrls":null,"recipient":null,"paymentUrl":"https://pay.pluggy.ai/05c693bf-c196-47ea-a28c-8251d6bb8a06"},"connector":{"id":603,"name":"Bradesco","primaryColor":"e5173f","institutionUrl":"https://banco.bradesco/open-finance/logo/icones_vetorial-pf.svg","country":"BR","type":"PERSONAL_BANK","credentials":[{"validation":"^\\d{3}\\.?\\d{3}\\.?\\d{3}-?\\d{2}$","validationMessage":"CPF deve ter 11 números.","label":"CPF","name":"cpf","type":"number","placeholder":"","optional":false}],"imageUrl":"https://cdn.pluggy.ai/assets/connector-icons/203.svg","hasMFA":false,"oauth":true,"health":{"status":"ONLINE","stage":null},"products":["ACCOUNTS","TRANSACTIONS","IDENTITY","CREDIT_CARDS","PAYMENT_DATA","LOANS","INVESTMENTS"],"createdAt":"2023-07-12T20:20:17.253Z","isSandbox":false,"isOpenFinance":true},"consentUrl":"https://consenturl.com"}
                    ]
            )
        else:
            return PaymentIntentsList200Response(
        )
        """

    def testPaymentIntentsList200Response(self):
        """Test PaymentIntentsList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
