# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.smart_accounts_list200_response import SmartAccountsList200Response

class TestSmartAccountsList200Response(unittest.TestCase):
    """SmartAccountsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmartAccountsList200Response:
        """Test SmartAccountsList200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmartAccountsList200Response`
        """
        model = SmartAccountsList200Response()
        if include_optional:
            return SmartAccountsList200Response(
                page = 1.337,
                total = 1.337,
                total_pages = 1.337,
                results = [
                    {"id":"71996b6d-8991-450c-8542-ae59069d1a9d","ispb":"0001020","agency":"1234","number":"123456","verifyingDigit":"7","type":"CHECKING_ACCOUNT","isSandbox":false}
                    ]
            )
        else:
            return SmartAccountsList200Response(
        )
        """

    def testSmartAccountsList200Response(self):
        """Test SmartAccountsList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
