# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.reserved_balance_remuneration import ReservedBalanceRemuneration

class TestReservedBalanceRemuneration(unittest.TestCase):
    """ReservedBalanceRemuneration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReservedBalanceRemuneration:
        """Test ReservedBalanceRemuneration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReservedBalanceRemuneration`
        """
        model = ReservedBalanceRemuneration()
        if include_optional:
            return ReservedBalanceRemuneration(
                pre_fixed_rate = 1.337,
                post_fixed_indexer_percentage = 1.337,
                rate_type = '',
                indexer = '',
                calculation = '',
                rate_periodicity = '',
                indexer_additional_info = ''
            )
        else:
            return ReservedBalanceRemuneration(
        )
        """

    def testReservedBalanceRemuneration(self):
        """Test ReservedBalanceRemuneration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
