# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.create_boleto_boleto_interest import CreateBoletoBoletoInterest

class TestCreateBoletoBoletoInterest(unittest.TestCase):
    """CreateBoletoBoletoInterest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBoletoBoletoInterest:
        """Test CreateBoletoBoletoInterest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBoletoBoletoInterest`
        """
        model = CreateBoletoBoletoInterest()
        if include_optional:
            return CreateBoletoBoletoInterest(
                value = 0,
                type = 'PERCENTAGE'
            )
        else:
            return CreateBoletoBoletoInterest(
                value = 0,
                type = 'PERCENTAGE',
        )
        """

    def testCreateBoletoBoletoInterest(self):
        """Test CreateBoletoBoletoInterest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
