# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.issued_boleto import IssuedBoleto

class TestIssuedBoleto(unittest.TestCase):
    """IssuedBoleto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssuedBoleto:
        """Test IssuedBoleto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssuedBoleto`
        """
        model = IssuedBoleto()
        if include_optional:
            return IssuedBoleto(
                id = '',
                amount = 2.5,
                status = 'OPEN',
                seu_numero = '',
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payer = pluggy_sdk.models.issued_boleto_payer.IssuedBoleto_payer(
                    tax_number = '', 
                    person_type = '', 
                    name = '', 
                    address_street = '', 
                    address_number = '', 
                    address_complement = '', 
                    address_neighborhood = '', 
                    address_city = '', 
                    address_state = '', 
                    address_zip_code = '', 
                    email = '', 
                    ddd = '', 
                    phone_number = '', ),
                pix_qr = '',
                digitable_line = '',
                nosso_numero = '',
                barcode = '',
                boleto_connection_id = ''
            )
        else:
            return IssuedBoleto(
                id = '',
                amount = 2.5,
                status = 'OPEN',
                seu_numero = '',
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payer = pluggy_sdk.models.issued_boleto_payer.IssuedBoleto_payer(
                    tax_number = '', 
                    person_type = '', 
                    name = '', 
                    address_street = '', 
                    address_number = '', 
                    address_complement = '', 
                    address_neighborhood = '', 
                    address_city = '', 
                    address_state = '', 
                    address_zip_code = '', 
                    email = '', 
                    ddd = '', 
                    phone_number = '', ),
                digitable_line = '',
                barcode = '',
                boleto_connection_id = '',
        )
        """

    def testIssuedBoleto(self):
        """Test IssuedBoleto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
