# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.other_document import OtherDocument

class TestOtherDocument(unittest.TestCase):
    """OtherDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OtherDocument:
        """Test OtherDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OtherDocument`
        """
        model = OtherDocument()
        if include_optional:
            return OtherDocument(
                type = 'CNH',
                type_additional_info = '',
                number = '',
                check_digit = '',
                additional_info = '',
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return OtherDocument(
                type = 'CNH',
                number = '',
        )
        """

    def testOtherDocument(self):
        """Test OtherDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
