# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.create_boleto_boleto_payer import CreateBoletoBoletoPayer

class TestCreateBoletoBoletoPayer(unittest.TestCase):
    """CreateBoletoBoletoPayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBoletoBoletoPayer:
        """Test CreateBoletoBoletoPayer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBoletoBoletoPayer`
        """
        model = CreateBoletoBoletoPayer()
        if include_optional:
            return CreateBoletoBoletoPayer(
                tax_number = '41.679.495/0001-00',
                name = 'NOME LEGAL EMPRESA',
                address_street = '',
                address_city = '',
                address_state = '',
                address_zip_code = ''
            )
        else:
            return CreateBoletoBoletoPayer(
                tax_number = '41.679.495/0001-00',
                name = 'NOME LEGAL EMPRESA',
                address_state = '',
                address_zip_code = '',
        )
        """

    def testCreateBoletoBoletoPayer(self):
        """Test CreateBoletoBoletoPayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
