# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.smart_account_address import SmartAccountAddress

class TestSmartAccountAddress(unittest.TestCase):
    """SmartAccountAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmartAccountAddress:
        """Test SmartAccountAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmartAccountAddress`
        """
        model = SmartAccountAddress()
        if include_optional:
            return SmartAccountAddress(
                address_type = 'residential',
                postal_code = '',
                street_name = '',
                street_number = '',
                city = '',
                state = '',
                is_primary_address = True,
                is_mailing_address = True
            )
        else:
            return SmartAccountAddress(
                city = '',
        )
        """

    def testSmartAccountAddress(self):
        """Test SmartAccountAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
