# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.automatic_pix_scheduler_configuration import AutomaticPixSchedulerConfiguration

class TestAutomaticPixSchedulerConfiguration(unittest.TestCase):
    """AutomaticPixSchedulerConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutomaticPixSchedulerConfiguration:
        """Test AutomaticPixSchedulerConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutomaticPixSchedulerConfiguration`
        """
        model = AutomaticPixSchedulerConfiguration()
        if include_optional:
            return AutomaticPixSchedulerConfiguration(
                enabled = True,
                description = '',
                value_for_variable_amount = 0.01
            )
        else:
            return AutomaticPixSchedulerConfiguration(
                enabled = True,
        )
        """

    def testAutomaticPixSchedulerConfiguration(self):
        """Test AutomaticPixSchedulerConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
