# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.page_response_acquirer_receivables import PageResponseAcquirerReceivables

class TestPageResponseAcquirerReceivables(unittest.TestCase):
    """PageResponseAcquirerReceivables unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageResponseAcquirerReceivables:
        """Test PageResponseAcquirerReceivables
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageResponseAcquirerReceivables`
        """
        model = PageResponseAcquirerReceivables()
        if include_optional:
            return PageResponseAcquirerReceivables(
                results = [
                    {"id":"71996b6d-8991-450c-8542-ae59069d1a9d","itemId":"9aab8d24-c89b-4b0e-8974-7dd5614686e4","description":"","currencyCode":"BRL","grossAmount":34,"netAmount":31.1,"date":"2023-10-02T03:00:00.000Z","paymentId":"123445567755353","destinationAccount":{"receivingBank":"Banco do Brasil S.A.","agency":"1234","account":"12345678-9"},"settlementStatus":"PAID","cardFlag":"VISA"}
                    ],
                page = 1.337,
                total = 1.337,
                total_pages = 1.337
            )
        else:
            return PageResponseAcquirerReceivables(
                results = [
                    {"id":"71996b6d-8991-450c-8542-ae59069d1a9d","itemId":"9aab8d24-c89b-4b0e-8974-7dd5614686e4","description":"","currencyCode":"BRL","grossAmount":34,"netAmount":31.1,"date":"2023-10-02T03:00:00.000Z","paymentId":"123445567755353","destinationAccount":{"receivingBank":"Banco do Brasil S.A.","agency":"1234","account":"12345678-9"},"settlementStatus":"PAID","cardFlag":"VISA"}
                    ],
                page = 1.337,
                total = 1.337,
                total_pages = 1.337,
        )
        """

    def testPageResponseAcquirerReceivables(self):
        """Test PageResponseAcquirerReceivables"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
