# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.create_payment_request import CreatePaymentRequest

class TestCreatePaymentRequest(unittest.TestCase):
    """CreatePaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePaymentRequest:
        """Test CreatePaymentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePaymentRequest`
        """
        model = CreatePaymentRequest()
        if include_optional:
            return CreatePaymentRequest(
                amount = 1.337,
                description = '',
                callback_urls = {},
                recipient_id = '',
                customer_id = '',
                client_payment_id = ''
            )
        else:
            return CreatePaymentRequest(
                amount = 1.337,
        )
        """

    def testCreatePaymentRequest(self):
        """Test CreatePaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
