# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.payment_customer_type import PaymentCustomerType

class TestPaymentCustomerType(unittest.TestCase):
    """PaymentCustomerType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentCustomerType(self):
        """Test PaymentCustomerType"""
        # inst = PaymentCustomerType()

if __name__ == '__main__':
    unittest.main()
