# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.payroll_loan_response_client import PayrollLoanResponseClient

class TestPayrollLoanResponseClient(unittest.TestCase):
    """PayrollLoanResponseClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayrollLoanResponseClient:
        """Test PayrollLoanResponseClient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayrollLoanResponseClient`
        """
        model = PayrollLoanResponseClient()
        if include_optional:
            return PayrollLoanResponseClient(
                name = '',
                document = '',
                phone = '',
                addres_street = '',
                address_number = '',
                address_city = '',
                address_zip_code = '',
                address_state = ''
            )
        else:
            return PayrollLoanResponseClient(
        )
        """

    def testPayrollLoanResponseClient(self):
        """Test PayrollLoanResponseClient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
