# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.boleto import Boleto

class TestBoleto(unittest.TestCase):
    """Boleto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Boleto:
        """Test Boleto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Boleto`
        """
        model = Boleto()
        if include_optional:
            return Boleto(
                digitable_line = '',
                barcode = '',
                payer = pluggy_sdk.models.boleto_payer.BoletoPayer(
                    tax_number = '', 
                    name = '', ),
                recipient = pluggy_sdk.models.boleto_recipient.BoletoRecipient(
                    tax_number = '', 
                    name = '', ),
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                base_amount = 1.337,
                penalty_amount = 1.337,
                interest_amount = 1.337,
                discount_amount = 1.337,
                total_amount = 1.337,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Boleto(
                digitable_line = '',
                barcode = '',
                payer = pluggy_sdk.models.boleto_payer.BoletoPayer(
                    tax_number = '', 
                    name = '', ),
                recipient = pluggy_sdk.models.boleto_recipient.BoletoRecipient(
                    tax_number = '', 
                    name = '', ),
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                base_amount = 1.337,
                penalty_amount = 1.337,
                discount_amount = 1.337,
                total_amount = 1.337,
        )
        """

    def testBoleto(self):
        """Test Boleto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
