# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.webhooks_list200_response import WebhooksList200Response

class TestWebhooksList200Response(unittest.TestCase):
    """WebhooksList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhooksList200Response:
        """Test WebhooksList200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhooksList200Response`
        """
        model = WebhooksList200Response()
        if include_optional:
            return WebhooksList200Response(
                page = 1.337,
                total = 1.337,
                total_pages = 1.337,
                results = [
                    pluggy_sdk.models.webhook.Webhook(
                        id = '', 
                        url = '', 
                        event = 'all', 
                        disabled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return WebhooksList200Response(
        )
        """

    def testWebhooksList200Response(self):
        """Test WebhooksList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
