# coding: utf-8

"""
    Pluggy API

    Pluggy's main API to review data and execute connectors

    The version of the OpenAPI document: 1.0.0
    Contact: hello@pluggy.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pluggy_sdk.models.marital_status import MaritalStatus

class TestMaritalStatus(unittest.TestCase):
    """MaritalStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaritalStatus:
        """Test MaritalStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaritalStatus`
        """
        model = MaritalStatus()
        if include_optional:
            return MaritalStatus(
                code = 'SINGLE',
                additional_info = ''
            )
        else:
            return MaritalStatus(
                code = 'SINGLE',
        )
        """

    def testMaritalStatus(self):
        """Test MaritalStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
