
---
name: Publish Docs

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - "!gh-pages"
  workflow_dispatch:
  workflow_run:
    workflows: [Update Spec/SDK]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  publish-docs:
    name: Publish Documentation 📚 to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for publishing docs

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: '3.x'

    - name: Install requirements for documentation generation
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdoc -r lib/requirements.txt

    - name: Generate API documentation with pdoc
      run: |
        pdoc --output-dir ./apidocs lib/pluggy_sdk

    - name: Push API documentation to Github Pages
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate API documentation"
